### ISSUE TITLE
Can't select 2 persons to add relation

### ISSUE THREAD

**Issue by Noxmiles** [derbenx/nextcloud-familytree#1]
even when clicked "select multiple" it only selects the last person I clicked on. Also not working with ctrl, shift, alt. Only while creating a new Person there is a single connection between the before selected person.

**Comment by derbenx** [comment]
First, select multiple is kinda weird right now, it selects people that overlap**, turning it off only selects the topmost name.
I plan to add a select box and / or something soon, it will help when importing/sorting GED files that I'm currently working on. 

Second, you don't need to select two people to make a new person (for multiple reasons, adoption, for example only requires one). Plus, only the females actually birth the child. If the children have multiple fathers, just add it in the notes. ;)


** Enable select multiple, drag two or more names to overlap, click and drag in the overlapped areas. Yeah, I don't like it either, should be changed by the next update. ;)

**Comment by derbenx** [comment]
Select multiple was updated to work better, you still don't need two people to add a person.
