### ISSUE TITLE
Export as GED file

### ISSUE THREAD

**Issue by justinfiore** [derbenx/nextcloud-familytree#4]
Would be possible to have an "Export GED" button to convert from your internal JSON format to a GED file?

Or alternatively, is the JSON format you are using standard such that there is a tool that can convert to a GED File?

**Comment by derbenx** [comment]
I only just added the import over the last 2 months. :P It's still not done as good as I like, yet.

Currently, no, not from the JSON data alone. GED files require more data than I save in the JSON. On the other hand, I plan to add other features than GED supports. Going back and fourth with GED will lose some data if implemented.

However, if imported from a GED file, I do keep that data (needed to export) as I use it to sort the tree on import, but there's no way to edit it in my app. So, that said, it could be possible in the future, but it'll still be lossy if you use any unmatched features between the formats.
